### ISSUE TITLE
Error occurred when I added GTM

### ISSUE THREAD

**Issue by cichy380** [guzmanoj/ngx-onetrust#1]
When I added script of Google Tag Manager on my website I got error:

```
ERROR TypeError: element.getAttribute is not a function
    at altack-ngx-onetrust.js:296:152
    at FilterSubscriber._next (filter.js:26:1)
    at FilterSubscriber.next (Subscriber.js:49:1)
    at MapSubscriber._next (map.js:35:1)
    at MapSubscriber.next (Subscriber.js:49:1)
    at FilterSubscriber._next (filter.js:33:1)
    at FilterSubscriber.next (Subscriber.js:49:1)
    at altack-ngx-onetrust.js:285:1
    at Array.forEach (<anonymous>)
    at MutationObserver.<anonymous> (altack-ngx-onetrust.js:284:1)
```

**Comment by wall-street-dev** [comment]
Hi @cichy380 I will try to reproduce it on my end. Would mind providing some more details?

**Comment by wall-street-dev** [comment]
I think I know what is happening. I'll be releasing a new version in a few hours. Thank you!

**Comment by wall-street-dev** [comment]
@cichy380  please give it a try to version 1.3.0
I have also updated the workspace and library to be compatible with Angular 13. Let me know if that works!

**Comment by cichy380** [comment]
Hi. Thanks for quick reaction :)

Error gone! Thanks again!
