### ISSUE TITLE
Blocked by cors policy : Request header field traceparent is not allowed by Access-Control-Allow-Headers in preflight response

### ISSUE THREAD

**Issue by delitamakanda** [guzmanoj/ngx-onetrust#8]
Hi,

How could I unlock this problem? Thank you for your answer

Access to XMLHttpRequest at 'https://cdn.cookielaw.org/consent/<domain-id>.json' from origin 'http://www.domain.fr' has been blocked by CORS policy: Request header field traceparent is not allowed by Access-Control-Allow-Headers in preflight response.
polyfills.js:23 Uncaught TypeError: Cannot read properties of undefined (reading 'Domain')
    at d.setDomainIfBulkDomainEnabled (otSDKStub.js:1:5962)
    at d.getLocation (otSDKStub.js:1:6401)
    at s.onerror [as __zone_symbol__ON_PROPERTYerror] (otSDKStub.js:1:8824)
    at XMLHttpRequest.g (polyfills.js:23:12816)
    at Z.invokeTask (polyfills.js:23:8437)
    at fe.runTask (polyfills.js:23:3778)
    at H.invokeTask [as invoke] (polyfills.js:23:9496)
    at ie (polyfills.js:23:22300)
    at ce (polyfills.js:23:22609)
    at XMLHttpRequest.Oe (polyfills.js:23:22894)

**Comment by delitamakanda** [comment]
case resolved by excluding domain with correlationHeaderExcludedDomains
